name: Sync Nova branch daily

on:
  workflow_call:
    inputs:
      from_ci:
        type: boolean
        required: false
        default: true

  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Add GitLab remote and fetch fifteen branch
        run: |
          git remote add upstream https://github.com/Nova-Kernels/kernel_xiaomi_mt6785.git || true
          git fetch upstream fifteen

      - name: Sync Nova and Update branches
        run: |
          set -e
          new_commit=$(git rev-parse upstream/fifteen)
          echo "Latest upstream commit: $new_commit"

          # Nova Branch: Upstream ile senkronize et
          if git rev-parse --verify nova >/dev/null 2>&1; then
              git checkout nova
              current_nova_commit=$(git rev-parse HEAD)
          else
              git checkout -b nova upstream/fifteen
              current_nova_commit=""
          fi

          if [ "$current_nova_commit" != "$new_commit" ]; then
              echo "Updating nova branch..."
              git reset --hard upstream/fifteen
              git rm --cached .github/workflows/*.yml 2>/dev/null || true
              git add -A
              git commit -m "Sync nova with upstream" || echo "No changes"
              git push origin nova --force
          fi

          # Update Branch: SADECE update-nova.md
          if git rev-parse --verify update >/dev/null 2>&1; then
              git checkout update
              # Tüm dosyaları sil (update-nova.md hariç)
              git ls-files | grep -v 'update-nova.md' | xargs git rm -rfq 2>/dev/null || true
          else
              git checkout --orphan update
              git rm -rf .  # Orphan branch'deki tüm dosyaları sil
          fi

          # Yeni update-nova.md oluştur/güncelle
          current_time=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          echo "Commit: $new_commit" > update-nova.md
          echo "Checked at: $current_time" >> update-nova.md
          
          git add update-nova.md
          git commit -m "Update log: $new_commit"
          git push origin update --force

      - name: Clear older runs
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh run list -L400 --json databaseId -q '.[].databaseId' | tail -n+5 | xargs -IID gh api "repos/$GITHUB_REPOSITORY/actions/runs/ID" -X DELETE || :