name: Sync Nova branch daily

on:
  workflow_call:
    inputs:
      from_ci:
        type: boolean
        required: false
        default: true
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Add GitLab remote and fetch fifteen-fixed branch
        run: |
          git remote add upstream https://github.com/Nova-Kernels/kernel_xiaomi_mt6785.git || true
          git fetch upstream fifteen-fixed

      - name: Sync Nova branch
        run: |
          set -e
          new_commit=$(git rev-parse upstream/fifteen-fixed)
          echo "Latest upstream commit: $new_commit"

          if git rev-parse --verify nova >/dev/null 2>&1; then
              git checkout nova
              current_nova_commit=$(git rev-parse HEAD)
          else
              git checkout -b nova upstream/fifteen-fixed
              current_nova_commit=""
          fi

          if [ "$current_nova_commit" != "$new_commit" ]; then
              echo "Updating nova branch..."
              git reset --hard upstream/fifteen-fixed
              git rm --cached .github/workflows/*.yml 2>/dev/null || true
              git add -A
              git commit -m "Sync nova with upstream" || echo "No changes"
              git push origin nova --force
          else
              echo "Nova branch zaten güncel."
          fi

      - name: Clear older runs
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh run list -L400 --json databaseId -q '.[].databaseId' | tail -n+5 | xargs -IID gh api "repos/$GITHUB_REPOSITORY/actions/runs/ID" -X DELETE || :
