name: Sync Power branch daily

on:
  workflow_call:
    inputs:
      from_ci:
        type: boolean
        required: false
        default: true
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Add GitLab remote and fetch vic branch
        run: |
          git remote add upstream https://github.com/Saikrishna1504/kernel_xiaomi_mt6785.git || true
          git fetch upstream vic

      - name: Sync Power branch
        run: |
          set -e
          new_commit=$(git rev-parse upstream/vic)
          echo "Latest upstream commit: $new_commit"

          if git rev-parse --verify power >/dev/null 2>&1; then
              git checkout power
              current_power_commit=$(git rev-parse HEAD)
          else
              git checkout -b power upstream/vic
              current_power_commit=""
          fi

          if [ "$current_power_commit" != "$new_commit" ]; then
              echo "Updating power branch..."
              git reset --hard upstream/vic
              git rm --cached .github/workflows/*.yml 2>/dev/null || true
              git add -A
              git commit -m "Sync power with upstream" || echo "No changes"
              git push origin power --force
          else
              echo "Power branch zaten güncel."
          fi

      - name: Clear older runs
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh run list -L400 --json databaseId -q '.[].databaseId' | tail -n+5 | xargs -IID gh api "repos/$GITHUB_REPOSITORY/actions/runs/ID" -X DELETE || :
