name: Sync susfs branch daily

on:
  schedule:
    - cron: '0 16 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Add GitLab remote and fetch susfs branch
        run: |
          git remote add upstream https://github.com/wodanesdag/android_kernel_xiaomi_mt6785.git || true
          git fetch upstream susfs

      - name: Check for updates and sync branch
        run: |
          set -e
          new_commit=$(git rev-parse upstream/susfs)
          echo "Latest upstream commit: $new_commit"

          if git rev-parse --verify susfs >/dev/null 2>&1; then
              echo "Local susfs branch exists."
              git checkout susfs
          else
              echo "Local susfs branch does not exist. Creating it."
              git checkout -b susfs upstream/susfs
          fi
          
          if [ -f update.md ]; then
              recorded_commit=$(grep -m1 "^Commit:" update.md | awk '{print $2}')
              echo "Recorded commit in update.md: $recorded_commit"
          else
              echo "update.md does not exist. It will be created."
              recorded_commit=""
          fi
          
          if [ "$recorded_commit" = "$new_commit" ]; then
              echo "No new update. Exiting."
              exit 0
          else
              echo "New update detected. Updating branch."
              git reset --hard upstream/susfs
              
              # Workflow dosyalarını commit dışı bırak: Dosya varsa işlemleri uygula
              if [ -f .github/workflows/build-artifacts.yml ]; then
                  git rm --cached .github/workflows/build-artifacts.yml || true
                  git update-index --skip-worktree .github/workflows/build-artifacts.yml || true
              fi
              if [ -f .github/workflows/release-artifacts.yml ]; then
                  git rm --cached .github/workflows/release-artifacts.yml || true
                  git update-index --skip-worktree .github/workflows/release-artifacts.yml || true
              fi
              
              current_time=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
              echo "Commit: $new_commit" > update.md
              echo "Checked at: $current_time" >> update.md
              
              git add update.md
              git commit -m "Update susfs: new commit $new_commit at $current_time"
              git push origin susfs --force
          fi

      - name: Clear older runs
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh run list -L400 --json databaseId -q '.[].databaseId' | tail -n+5 | xargs -IID gh api "repos/$GITHUB_REPOSITORY/actions/runs/ID" -X DELETE || :
