name: Sync PowerFork branch daily

on:
  workflow_call:
    inputs:
      from_ci:
        type: boolean
        required: false
        default: true
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Add GitLab remote and fetch susfs branch
        run: |
          git remote add upstream https://github.com/wodanesdag/android_kernel_xiaomi_mt6785.git || true
          git fetch upstream susfs

      - name: Sync PowerFork branch
        run: |
          set -e
          new_commit=$(git rev-parse upstream/susfs)
          echo "Latest upstream commit: $new_commit"

          if git rev-parse --verify powerfork >/dev/null 2>&1; then
              git checkout powerfork
              current_powerfork_commit=$(git rev-parse HEAD)
          else
              git checkout -b powerfork upstream/susfs
              current_powerfork_commit=""
          fi

          if [ "$current_powerfork_commit" != "$new_commit" ]; then
              echo "Updating powerfork branch..."
              git reset --hard upstream/susfs
              git rm --cached .github/workflows/*.yml 2>/dev/null || true
              git add -A
              git commit -m "Sync powerfork with upstream" || echo "No changes"
              git push origin powerfork --force
          else
              echo "PowerFork branch zaten güncel."
          fi

      - name: Clear older runs
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh run list -L400 --json databaseId -q '.[].databaseId' | tail -n+5 | xargs -IID gh api "repos/$GITHUB_REPOSITORY/actions/runs/ID" -X DELETE || :
